### ISSUE TITLE
executeScript does not wait on chromeP.tabs.executeScript promise

### ISSUE THREAD

**Issue by twschiller** [fregante/webext-content-scripts#22]
- Currently, `executeScript` will await `chromeP.tabs.executeScript` promises if there are multiple scripts, but doesn't await/return the last promise 
- I think lastInjection needs to be returned
- https://github.com/fregante/webext-content-scripts/blob/main/index.ts#L154
- As a workaround, I'm going to try passing multiple scripts, so that the one I care about is await

**Comment by twschiller** [comment]
Actually, re-reading the function, it doesn't wait or return the promise at all if you pass it files

**Comment by fregante** [comment]
Indeed insertCSS awaits `everyInsertion` but executeScript does not. Will fix soon
